import p1 from "./assets/images/p1.png";
import p2 from "./assets/images/p2.png";

const bestSeller = [
  {
    image: p1,
    name: "Adidas",
    subhead: "Men's Shoe LEONAL",
    rating: 4,
    price: 11302,
    size: 7,
    colour: "Brown",
  },
  {
    image: p2,
    name: "Nike",
    subhead: "Mens's Shoe MAX",
    rating: 1,
    price: 6086,
    size: 8,
    colour: "Brown",
  },
  {
    image: p1,
    name: "Adidas",
    subhead: "Men's Shoe LEONAL",
    rating: 4,
    price: 11302,
    size: 7,
    colour: "Red",
  },
  {
    image: p2,
    name: "Nike",
    subhead: "Mens's Shoe MAX",
    rating: 1,
    price: 6086,
    size: 7,
    colour: "Brown",
  },
  {
    image: p1,
    name: "Adidas",
    subhead: "Men's Shoe LEONAL",
    rating: 4,
    price: 11302,
    size: 7,
    colour: "Brown",
  },
  {
    image: p2,
    name: "Nike",
    subhead: "Mens's Shoe MAX",
    rating: 1,
    price: 6086,
    size: 7,
    colour: "Brown",
  },
  {
    image: p1,
    name: "Adidas",
    subhead: "Men's Shoe LEONAL",
    rating: 4,
    price: 11302,
    size: 7,
    colour: "Brown",
  },
  {
    image: p2,
    name: "Nike",
    subhead: "Mens's Shoe MAX",
    rating: 1,
    price: 6086,
    size: 7,
    colour: "Brown",
  },
  {
    image: p1,
    name: "Adidas",
    subhead: "Men's Shoe LEONAL",
    rating: 4,
    price: 11302,
    size: 7,
    colour: "Brown",
  },
  {
    image: p2,
    name: "Nike",
    subhead: "Mens's Shoe MAX",
    rating: 1,
    price: 6086,
    size: 7,
    colour: "Brown",
  },
  {
    image: p1,
    name: "Adidas",
    subhead: "Men's Shoe LEONAL",
    rating: 4,
    price: 11302,
    size: 7,
    colour: "Brown",
  },
  {
    image: p2,
    name: "Nike",
    subhead: "Mens's Shoe MAX",
    rating: 1,
    price: 6086,
    size: 7,
    colour: "Brown",
  },
];

export default bestSeller;
